### ISSUE TITLE
nested components with overridable style

### ISSUE THREAD

**Issue by itajaja** [Khan/aphrodite#110]
The pattern I use for nested components with overridable style is usually something like:

```js
function Foo({ className }) {
  return <div className={css(fooStyle, className)} />;
}
```

so then I can use Foo like

```js
function Bar() {
  return <Foo className={barStyle} />;
}
```

what if also want `Bar's` style to be overrideable? I don't see a way to currently do that. A solution would be for `css` to accept arrays of styles, so that `Bar` can be written as

```
function Bar({ className }) {
  return <Foo className={[barStyle, className]} />;
}
```

so that the final (unrolled) arguments to `Foo`'s `css` will be `css(fooStyle, [barStyle, className])` that would be equivalent to the flattened `css(fooStyle, barStyle, className)`. Probably there are other solutions, but this is the simplest one I could think of. Am I missing something?

**Comment by kylpo** [comment]
Hey @itajaja, thanks for asking this question, as I have wondered how to do this myself (this is actually what kept me using Radium). This morning, I think I found a reasonable solution though. 

Can you do something like:
```js
import classnames from 'classnames'

function Foo({ className }) {
  return <div className={classnames(css(fooStyle), className)} />;
}

function Bar({ className }) {
  return <Foo className={classnames(css(barStyle), className)} />;
}
```

This is using Aphrodite's `css()` to return a classname, then `classnames()` to combine multiple classname strings into one, which react's `className` will use.

Note: I have not tried this yet. Just recently thought of this approach.

**Comment by kentcdodds** [comment]
One thing that I've done is allow people to compose in their own styles like this:

```jsx
function Foo({ buttonStyles }) {
  const styles = StyleSheet.create({
    button: {
      color: 'blue',
      padding: 20,
      // etc.
      ...buttonStyles
    }
  })
  return (
    <div>
      <button className={css(styles.button)}>Click me</button>
    </div>
  )
}

function Bar() {
  const buttonStyles = {
    color: 'green',
    // etc.
  }
  return <Foo buttonStyles={buttonStyles} />
}
```

**Comment by xymostech** [comment]
@itajaja Thanks for your question!

At Khan Academy, we have components that take an array of Aphrodite styles, sorta like your last example. We also make heavy use of array/rest spread in that case, which is why we don't need `css` to accept arrays. We also tend to call the prop something like `styles` or `extraStyles`, since they are styles, not class names. So for instance, your example might look like:

```jsx
function Foo({extraStyles}) {
    return <div className={css(styles.foo, ...extraStyles)} />;
}

function Bar({extraStyles}) {
    return <Foo extraStyles={[styles.bar, ...extraStyles]} />;
}
```

and then you could use

```
<Bar extraStyles={[styles.differentBar]} />
```

and things will do what you expect (that is, `styles.bar` overrides `styles.foo`, and `styles.differentBar` overrides both of them). Does that answer your question?

@kylpo

> This is using Aphrodite's css() to return a classname, then classnames() to combine multiple classname strings into one, which react's className will use.

This isn't a good solution, because of how Aphrodite's classnames work. In order to ensure that the correct styles take precedence, you need to put all of your styles into one call to `css()`.

(I'm going to go make a pull request to add this to the Caveats section of the readme now, since a lot of people make this mistake)

**Comment by itajaja** [comment]
@xymostech That's a very good solution! I also like the fact that it makes a clear convention of what is being passed. `className` prop is always a string, while `styles` is an aphrodite style

**Comment by xymostech** [comment]
I'm going to close this, since this isn't an issue with aphrodite itself. Maybe we should move the results of these kinds of discussions into the wiki or something?
