### ISSUE TITLE
Feature comparison

### ISSUE THREAD

**Issue by nachoaIvarez** [Khan/aphrodite#128]
How this compares with [Radium](https://github.com/FormidableLabs/radium)?

I really like the approach Aphrodite has, and it would really help if you could point out differences, advantages/disadvantages in comparison with Radium, that looks really similar!

I guess the API being similar to the React Native one is one of them, and also the lack of decorators (not quite there yet in terms of es spec) or less boilerplate code (no need to wrap every single component on a Radium instance).

Thanks!

**Comment by kentcdodds** [comment]
Here's 3 minutes of what I have to say about how it compares: [
Q&A: Aphrodite vs. Radium](https://www.briefs.fm/3-minutes-with-kent/28) :)

**Comment by xymostech** [comment]
I would say that, regardless of small differences in the API, the biggest difference is that Aphrodite actually generates CSS and thus can use lots of features that CSS has, like `::after` or `:visited`, which Radium doesn't support. It also means that when server-side rendering, things like `:hover` or `:active` will work in Aphrodite, but not in Radium which requires JavaScript to work.

Also, Aphrodite isn't React-specific, it can work with any system that generates HTML.

There's a repo which has some comparisons between different CSS in JS libraries, which you can find here: https://github.com/MicheleBertoli/css-in-js

I'm going to close this since it isn't a bug in Aphrodite, but feel free to continue the discussion. :)
