### ISSUE TITLE
[Question] Does Aphrodite works in MERN Stack?

### ISSUE THREAD

**Issue by vizFlux** [Khan/aphrodite#134]
Hi,

Does it work with MERN stack? I've been getting `error: Cannot automatically buffer without a document` on the server side.

**Comment by xymostech** [comment]
I haven't used a MERN stack before, but it should work. You need to follow the [instructions about server-side rendering](https://github.com/khan/aphrodite#server-side-rendering) in order to get things to work probably.

I dont know what your setup looks like, but just looking at the [server code in the MERN starter pack](https://github.com/Hashnode/mern-starter/blob/master/server/server.js), you would probably need to do something like this:

Wrap the call to `ReactDOMServer.renderToString` in Aphrodite's `StyleSheet.renderStatic`, :
```
        const {initialView, css} = StyleSheet.renderStatic(() => renderToString(
            <Provider store={store}>
              <IntlWrapper>
                <RouterContext {...renderProps} />
              </IntlWrapper>
            </Provider>
          )
        );
        const finalState = store.getState();

        res
          .set('Content-Type', 'text/html')
          .status(200)
          .end(renderFullPage(initialView, css, finalState)); // Note we pass the `css` result into `renderFullPage`
```

Add a CSS function to the `renderFullPage` function, and put the `css.content` styles into a stylesheet, as well storing the rendered class names in a global.
```
// Render Initial HTML
const renderFullPage = (html, css, initialState) => {
  const head = Helmet.rewind();

  // Import Manifests
  const assetsManifest = process.env.webpackAssets && JSON.parse(process.env.webpackAssets);
  const chunkManifest = process.env.webpackChunkAssets && JSON.parse(process.env.webpackChunkAssets);

  return `
    <!doctype html>
    <html>
      <head>
        <style data-aphrodite>${css.content}</style> <!-- Add stylesheet here -->
  ...
        <script>
          window.__INITIAL_STATE__ = ${JSON.stringify(initialState)};
          window.__INITIAL_RENDERED_CLASSNAMES__ = ${JSON.stringify(css.renderedClassNames)}; // Add classnames global here.
        </script>
  ...
    </html>
  `;
}
```

Do Aphrodite rehydration before we try to rehydrate on the client: (from [the client entry point](https://github.com/Hashnode/mern-starter/blob/master/client/index.js))
```
// Initialize store and Aphrodite
const store = configureStore(window.__INITIAL_STATE__);
StyleSheet.rehydrate(window.__INITIAL_RENDERED_CLASSNAMES__); // Aphrodite rehydration
const mountApp = document.getElementById('root');
```

Hope that helps! (I'm going to close this issue because it's not related to a bug in Aphrodite, but feel free to continue the discussion here)

**Comment by vizFlux** [comment]
@xymostech

Appreciate very much about your time taken to go through this, it works like charm! One thing to note is that we should wrap it using `StyleSheetServer.renderStatic` instead of `StyleSheet.renderStactic`. Many thanks man!

**Comment by xymostech** [comment]
Oops, you're right about `StyleSheetServer`! I'll update my comment...
