### ISSUE TITLE
Flickering / performance issue with touch events

### ISSUE THREAD

**Issue by bkgunby** [Khan/aphrodite#137]
The component in question is a simple progress bar where the user can drag it like a slider. I am depending on the component's state that will in turn call `StyleSheet.create()` with the updated position: `translateX(-${100-state.progress}%)`. However, there seems to be some flickering issues when I drag it using my phone (it works fine on the desktop's mobile emulator). Everything behaves accordingly except that the progress bar itself will flicker a few times during the `touchmove` event. I am also throttling my handler, but that doesn't help.

The reason why I bring the issue here is because I was able to fix this by modifying the style directly using a ref: `this.progressBarRef.style.webkitTransform`. Is this a known issue, where calling StyleSheet.create() too many times can cause performance overhead on a mobile device? Possibly something else?

**Comment by jlfwong** [comment]
In cases where you have a rapidly changing property, running a new `StyleSheet.create()` call on every change will indeed yield poor performance, because the associated `css()` call on the properties of the `StyleSheet.create` call might inject some new CSS into the DOM.

In the case of rapidly changing properties, the s
