### ISSUE TITLE
Add a RunKit example

### ISSUE THREAD

**Issue by xymostech** [Khan/aphrodite#140]
I noticed that there's a way to add a default example to the RunKit (formerly TonicDev?) example that for a repository: https://discuss.runkit.com/t/customizing-your-npm-packages-page-on-tonic/23

It would be cool if we added one of these for Aphrodite! I came up with a server-side rendering example that we could use: https://runkit.com/xymostech/aphrodite-server-side-rendering-example I tried to make a non-server-side-rendering example but it required jsdom and a `setTimeout` which was pretty ugly. 

Thoughts?

**Comment by jlfwong** [comment]
Seems fine to me! I have a very mild aversion to changing things in the repo for integration with random third party services, but my aversion is mostly against doing work that gets requested of maintainers because a new service is spun up, or a new library is release, or a breaking change is made to that third party service. So as long as all I have to do is say "LGTM", go for it :P
