### ISSUE TITLE
regular classes + aphrodite?

### ISSUE THREAD

**Issue by acomito** [Khan/aphrodite#144]
I need to add an 'active' class based on a components local state. How would I do this with aphrodite while still using `css(styles.myClass)` ?

e.g.

```
<Button 
className={this.state.myState ? 'active' : null} //what I would do if I didn't need aphrodite styles
className={css(styles.tabButton)} //how to use my aphrodite tabButton style, but append the active class when needed?
>
Open
</Button>
```

**Comment by xymostech** [comment]
You can just concatenate class names in the `className` prop, since `css()` just returns a normal class name:

```jsx
<Button
className={(this.state.myState ? 'active ' : '') + css(styles.tabButton)}
>
Open
</Button>
```

If you are trying to add extra Aphrodite styles depending on `this.state.myState`, you can just call `css(styles.tabButton, this.state.myState && styles.activeStyles)` or something like that, since the `css()` function filters out falsey values.
