### ISSUE TITLE
Styles should be global or local?

### ISSUE THREAD

**Issue by hnordt** [Khan/aphrodite#17]
Hello.

Sorry for the newbie question, but what's the best practice?

1. Each component should define their own CSS rules. ComponentA can contain green style, ComponentB can contain green style too, but ComponentA green style properies can be different of ComponentB green style properties.
2. Styles should be global, I can create a styles.js file and use it inside components.

**Comment by xymostech** [comment]
It's really up to you, aphrodite doesn't have strong opinions. If your green styles are different, then they will produce different results when class names are generated for them, so you shouldn't have to worry about them being the same.

I'd suggest you have component-local styles just because it will be easier to mange them and keep yourself sane and you can have shorter style names, but there's no technical preference between the two.

**Comment by hnordt** [comment]
Thank you @xymostech
