### ISSUE TITLE
Support 'animation-name' alongside 'animationName' for @keyframes

### ISSUE THREAD

**Issue by nickbreaton** [Khan/aphrodite#170]
It is my understanding that the two following ways to write styles are both considered appropriate:

```js
StyleSheet.create({
  icon: {
    'background-color': 'blue'
  }
});
```
```js
StyleSheet.create({
  icon: {
    'backgroundColor': 'blue'
  }
});
```

If I am correct in my understanding, then the following should work:
```js
StyleSheet.create({
  icon: {
    'animation-name': spin
  }
});
```
```js
StyleSheet.create({
  icon: {
    'animationName': spin
  }
});
```

However, `animation-name` seems to not work. The resulting CSS looks like:
```
animation-name: [object Object] !important;
```

This leads me to believe that the animation is not being parsed. 

If I am incorrect in my assumption that `animation-name` should be parsed the same as `animationName` I apologize.

**Comment by jlfwong** [comment]
Hi @nickbreaton!

The kebab-case way works coincidentally for other properties at the moment, but was not something we intentionally intended to support. (It works because we do the conversion from camelCase to kebab-case automatically, and if that result is a no-op, it's okay).

I don't have a particularly strong interest in supporting this for `animationName`, but don't have a strong opposition to it being done if the change is small and simple.

**Comment by nickbreaton** [comment]
@jlfwong I appreciate the quick response. I apologize for not understanding that kebab-case was not intentionally supported. Thank you for the clarification. 

Knowing this is the case, I agree with not making a change. I'm going to go ahead and close the issue. 

Thanks for all the hard work. :+1:
