### ISSUE TITLE
Silent failure

### ISSUE THREAD

**Issue by TylerK** [Khan/aphrodite#184]
Just a heads up, I noticed that the following block of code was failing silently, and preventing any subsequent styles from being applied:

```
const styles = StyleSheet.create({
  wrapper: {
    textAlign: 'center',
    margin: `calc(100% - ${sizes.medium}`,
  }
});
```

Notice the missing `)`. No errors were output to the console or browser.

**Comment by jlfwong** [comment]
Hi @TylerK,

Yeah, it's a bit unfortunate. Sorry you ran into trouble here!

Fixing this and more generally doing validation of CSS property values would involve including a full CSS validator in aphrodite, which would significantly bloat the codesize of the library. In the past, we've decided against pursuing this path.

Doing that may be feasible if we made separate debug and prod builds, but we're not at the moment.

**Comment by xymostech** [comment]
As an aside: we've been throwing around the idea of using `StyleSheet.insertRule`, and I have a PR that I'm going to send out at some point which uses it. I think that change would successfully solve this problem, since the browser will complain if you try to insert malformed CSS. That won't happen during server-side style generation, though.
