### ISSUE TITLE
Does this work in vuejs ?

### ISSUE THREAD

**Issue by agnivade** [Khan/aphrodite#237]
I was looking for a proper inline css solution in vuejs. And this seems like a good choice.

**Comment by xymostech** [comment]
I haven't used Vue before, but it looks like you could just pass in the generated classname and use `v-bind:class`:

```html
<div id="app">
  <p v-bind:class="classname">{{ message }}</p>
</div>
```

```js
const styles = StyleSheet.create({
  red: {
    color: "red",
  },
});

new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue.js!',
    classname: css(styles.red),
  }
})
```

So, the answer is "yes, it does work in Vue". That said, it's not terribly pretty, but you could probably make it nicer by writing a directive. For instance, you could maybe do

```html
<div id="app">
  <p v-style="[styles.red, styles.big]">{{ message }}</p>
</div>
```

```js
Vue.directive('style', {
  bind: function(el, binding) {
    el.className = css(binding.value);
  },
});

new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue.js!',
    styles: StyleSheet.create({
      red: {
        color: "red",
      },
      big: {
        fontSize: "30px",
      },
    }),
  }
})
```

(I'm going to close this issue because it's not related to an actual bug in the project. Feel free to continue the discussion here though!)

**Comment by agnivade** [comment]
Thanks. That looks good.

**Comment by joshwcomeau** [comment]
That looks good to me! I've worked with Vue a bit and I think it could couple nicely with Aphrodite :)

@agnivade let me know how this works out for you. It may be worth creating "official" bindings, especially if it requires further massaging (or if you come up with any improvements).

cc @xymostech
