### ISSUE TITLE
Question on conditional @font-face rule

### ISSUE THREAD

**Issue by dangodev** [Khan/aphrodite#283]
In the README, the following is stated:

> In the case of Aphrodite we only want to insert that rule if it's actually being referenced by a class that's in the page.

`@font-face` only requests fonts **if** that font is being used on the page. It won’t request all fonts used in the CSS, even if the styles are declared, unless that font is actually required for paint. In theory, you can have as many `@font-face` declarations as you’d like loaded onto the page, but only the fonts actually being used on that page are requested & downloaded.

What’s the purpose of essentially doing double-work the browser is already doing? Are there any common use cases where there are hundreds of `@font-face` declarations? It seems unlikely.

**Comment by xymostech** [comment]
One of the goals of Aphrodite is to generate the smallest amount of CSS in order to render a given page. That goal was defined so that with server-side rendering would let your pages download the fewest bytes to render correctly. So you're right, we could insert those rules and there wouldn't be any problems, but it wouldn't match our goals.

From a technical side though, Aphrodite doesn't look at the rules that you write until `css()` call time. So, we currently don't ever attempt to insert anything until you generate a class name.

Hopefully that answers your question? I'm going to close this since this doesn't represent a bug in Aphrodite itself, but please continue the discussion here if you have more to say!

**Comment by dangodev** [comment]
That makes a lot of sense. I initially read that as if it were specific to `@font-face`, not the general goal you described. Though I don’t know how you would change that language to be clearer.

Thanks for answering my question!
