### ISSUE TITLE
Why is there this smiley o_O everywhere ?

### ISSUE THREAD

**Issue by Soreine** [Khan/aphrodite#337]
This is just a question.

I see this kind of classnames in DEV `image_gcxn8f-o_O-avatar_pjue4n `

I understand that aphrodite hashes style names togethers into a unique classname, and preserve the original style names in DEV. That's why we see names and hashes alternating. But what's the purpose of having `o_O` 😄  ?

**Comment by jlfwong** [comment]
Haha, this is a bit of weird historical stuff.

This bit of code was written in the first couple hours I was working on this with @xymostech -- we saw the lack of SSR support & media query support in other CSS-in-JS solutions and thought we could sketch out a rough solution that would do better in a few hours.

The reason that there's a separator here of `o_O` is because we needed a separator that was very unlikely to occur in anyone's actually CSS class names. The original version of aphrodite included a global counter rather than hashes while we were still figuring out aphrodite support.

So it would originally have been something like: `image1-o_O-avatar2`.

The reason it was important that the separator to not occur in the class name was to avoid collisions. If we had chosen, to just concatenate, then the concatenation of

`a1b2b3` either could have been the concatenation of `a`, `b`, `c` + the counter values, or could it be the concatenation of `a`, `b2b` with counter values. Our bet was that nobody would use `-o_O-` as part of their CSS class names 😛
