### ISSUE TITLE
.listItem + .listItem

### ISSUE THREAD

**Issue by marcusnielsen** [Khan/aphrodite#77]
Any advice on how to get `marginBottom: 50` as in this snippet with `.listItem + .listItem`?
```
      listItem: {
        '@media (min-width: 600px)': {
          width: `${HUNDRED_PERCENT / itemsCount}%`,
          marginBottom: 0,
          display: 'inline-block'
        },
        display: 'block',
        width: '100%',
        textAlign: 'center',
         'listItem + listItem': { // NOTE: How do I do this one here?
           marginBottom: 50 
          }
      }
    })
```

EDIT: Clarified some stuff. Note that some CSS props might be removable. I'm a bit CSS-rusty these days.

**Comment by jlfwong** [comment]
Hi @marcusnielsen!

You can selectively apply the `marginBottom` for cases when the `listItem` follows another list item.

So in your example, you'd do something like this:

```
const styles = StyleSheet.create({
    listItem: {
        ... your styles go here
    },
    listItemOtherThanFirst: {
        marginBottom: 50
    }
});

const component = (things) => <div>
    {things.map((t, i) => <p className={css(styles.listItem, i > 0 && styles.listItemOtherThanFirst)}>
       {t}
    }</p>
</div>;
```

In general, we restrict Aphrodite to features that are cannot be be emulated at render() (as opposed to `componentDidMount` time). `+` is possible to emulate at `render()` time, as shown above. For instance, `:hover` and `@media` queries cannot be emulated at `render()` time, because they require information about the state of the browser.

**Comment by marcusnielsen** [comment]
Even better answer than expected!
